import { AccMap } from './type';

export const imprintOptions = [
  'Awakening',
  'thirst',
  'Necromancer',
  'Enhanced Weapon',
  'Fortified Shield',
  'The price of the duel',
  'The Lonely Knight',
  'Madness',
  'The Secret of the Berserker',
  'Beads',
  'hard will',
  'The Dramatic: Chessul',
  'Vital hit',
  'The price of surprise',
  'Emergency Rescue',
  'Full of sympathy',
  'Sound of the Moon',
  'The power of a master',
  'Assault Captain',
  'Second Colleague',
  'Increase mana efficiency',
  'flow of mana',
  'blossom',
  'Unstoppable impulse',
  'barricade',
  'burst',
  'Wrath of Lightning',
  'broken bones',
  'The Hammer of Wrath',
  'Fist of Crushing',
  'Indomitable',
  'Time to Hunt',
  'Advanced Summoner',
  'Players Victory',
  'Semac-Tatong',
  'Quickly fast-paced',
  'Super Charge',
  'winner',
  'focus your attention',
  'Shield Penetration',
  'The Judge',
  'adrenaline',
  'Artetains Skill',
  'steady state',
  'ignore the abbreviation',
  'Aether Predator',
  'Goddess Blessing',
  'Reverse heavenly delay',
  'A sharp blunt weapon',
  'Strengthening of the O',
  'Rumbling of Five',
  'complete suppression',
  'resentment',
  'Avoiding a crisis',
  'one blow kill',
  'Residual energy',
  'Cursed Doll',
  'specialist',
  'Battle Stance',
  'Desperate Salvation',
  'zenith',
  'moderation',
  'ignition',
  'regular absorption',
  'precision dagger',
  'Death Attack',
  'wear heavy armor',
  'gravity training',
  'True Valor',
  'The Legacy of Evolution',
  'increase in mass',
  'beginner',
  'Increase max mana',
  'driving force',
  'Aura of Blessing',
  'Shock training',
  'The price of the blow',
  'The Master of Escape',
  'Strengthening bombardment',
  'Explosives expert',
  'Peace Maker',
  'Hand Gunner',
  'Strengthening firepower',
  'reflux',
  'Emperors Edict',
  'The Empress Grace',
  'return',
];

export const penaltyOptions = [
  'Attack reduction',
  'Attack Speed Reduction',
  'Defense reduction',
  'Reduce movement speed',
];

export const dealOptions = ['Lethal', 'Specialization', 'Suppression', 'Quick', 'Patience', 'Skill'];

export const itemNames = [
  'Necklace of Fallen Time',
  'A necklace of howling chaos',
  'Brilliant Seekers Necklace',
  'A necklace of burning will',
  'Necklace of Fallen Wisdom',
  'Howling Fantasy Necklace',
  'Brilliant Executioners Necklace',
  'Necklace of Empty Destiny',
  'Necklace of Cruel Destruction',
  'Necklace of the Holy Guardian',
  'Necklace of the Soaring Will',
  'Earrings of Fallen Time',
  'Earrings in the Fallen Space',
  'Earrings of howling chaos',
  'Howling Earrings of Eternity',
  'The Brilliant Seekers Earring',
  'Brilliant Destroyers Earrings',
  'Earring of the burning will',
  'Earrings of Burning Faith',
  'Earrings of Fallen Wisdom',
  'Earrings of the Fallen Dimension',
  'The earring of a howling fantasy',
  'Earring of a howling nightmare',
  'Brilliant Executioners Earrings',
  'Brilliant Pilgrims Earrings',
  'Earrings of Empty Destiny',
  'Earring of an empty relationship',
  'Earrings of Grievous Doom',
  'Earrings of the Terrible End',
  'Earrings of the Holy Guardian',
  'Earring of the Holy Liberator',
  'Earrings of the Soaring Will',
  'Earrings of Soaring Faith',
  'Ring of Fallen Time',
  'Ring of Fallen Space',
  'The Ring of Howling Chaos',
  'The ring of eons howling',
  'The Brilliant Seekers Ring',
  'Ring of the Brilliant Destroyer',
  'Ring of the Burning Will',
  'Ring of Burning Faith',
  'Ring of Corrupted Wisdom',
  'Ring of the Fallen Dimension',
  'The ring of howling illusion',
  'The Ring of Howling Nightmares',
  'Ring of the Brilliant Executioner',
  'The Brilliant Pilgrims Ring',
  'Ring of Destiny',
  'Ring of an empty bond',
  'Ring of Grievous Doom',
  'Ring of the Cruel End',
  'The Ring of the Holy Guardian',
  'The Ring of the Holy Liberator',
  'Ring of the Soaring Will',
  'Ring of Soaring Faith',
];

export const initialAccMap: Record<string, AccMap> = {
  목걸이: {
    category: 'necklace',
    quality: 50,
    dealOption1: ['', 0],
    dealOption2: ['', 0],
    name: '',
    imprintOption1: ['', 0],
    imprintOption2: ['', 0],
    imprintPenalty: ['', 0],
  },
  귀걸이1: {
    category: 'earring',
    quality: 50,
    dealOption1: ['', 0],
    name: '',
    imprintOption1: ['', 0],
    imprintOption2: ['', 0],
    imprintPenalty: ['', 0],
  },
  귀걸이2: {
    category: 'earring',
    quality: 50,
    dealOption1: ['', 0],
    name: '',
    imprintOption1: ['', 0],
    imprintOption2: ['', 0],
    imprintPenalty: ['', 0],
  },
  반지1: {
    category: 'ring',
    quality: 50,
    dealOption1: ['', 0],
    name: '',
    imprintOption1: ['', 0],
    imprintOption2: ['', 0],
    imprintPenalty: ['', 0],
  },
  반지2: {
    category: 'ring',
    quality: 50,
    dealOption1: ['', 0],
    name: '',
    imprintOption1: ['', 0],
    imprintOption2: ['', 0],
    imprintPenalty: ['', 0],
  },
};

export const imprintingFormToken = 'imprintingForm_v4';
